CREATE EXTENSION IF NOT EXISTS ISN;

CREATE TABLE IF NOT EXISTS Books (id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    url VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    content bytea,
    isbn ISBN)